import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
import { root, loadEntries, selectEntries, renderEntry, createPageContext } from './content.mjs';
import { checkAssets, sceneHead } from './assets.mjs';
const entries=await loadEntries();
const selected=selectEntries(entries,{drafts:true});
const context=createPageContext();
const fragments=await Promise.all(selected.map((e,i)=>renderEntry(e,selected[i+1],new Date(),context)));
const shell=await readFile(new URL('src/shell.html',root),'utf8');
const html=shell.replace('{{entries}}',()=>fragments.join('\n')).replace('{{firstId}}',selected[0]?.id ?? 'top').replace('{{sceneHead}}',sceneHead(selected,context));
const assets=await checkAssets(selected,html);
const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);
assert.equal(ids.length,new Set(ids).size,'Duplicate HTML IDs');
for(const [,id] of html.matchAll(/href="#([^"]+)"/g)) assert(ids.includes(id),`Broken anchor #${id}`);
console.log(`Validated ${entries.length} content records, ${assets.length} owned assets, and all review-page anchors.`);
