import { readFile, stat } from 'node:fs/promises';
import assert from 'node:assert/strict';
import { root, loadEntries, selectEntries, renderEntry } from './content.mjs';
const entries=await loadEntries();
const selected=selectEntries(entries,{drafts:true});
const fragments=await Promise.all(selected.map((e,i)=>renderEntry(e,selected[i+1],new Date())));
const shell=await readFile(new URL('src/shell.html',root),'utf8');
const html=shell.replace('{{entries}}',()=>fragments.join('\n')).replace('{{firstId}}',selected[0]?.id ?? 'top');
const css=await readFile(new URL('public/styles.css',root),'utf8');
const refs=new Set([...`${html}\n${css}`.matchAll(/assets\/[\w.-]+/g)].map(m=>m[0]));
for(const file of ['app.js','crunch.js','discoveries.js','styles.css','assets/chip-a.mp3','assets/chip-b.mp3',...refs]) assert((await stat(new URL('public/'+file,root))).isFile(),`Missing asset ${file}`);
const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);
assert.equal(ids.length,new Set(ids).size,'Duplicate HTML IDs');
for(const [,id] of html.matchAll(/href="#([^"]+)"/g)) assert(ids.includes(id),`Broken anchor #${id}`);
console.log(`Validated ${entries.length} content records, ${refs.size} assets, and all review-page anchors.`);
