import assert from 'node:assert/strict';
import {createHash,randomUUID} from 'node:crypto';
import {readFile,writeFile,readdir,mkdir,rename,rm,open} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {root,validate,contentDigest,fragmentEditorialContent,selectRelease,esc} from './content.mjs';
import {createDesk} from './candidates.mjs';
import {shareCopy} from './share-copy.mjs';
import {entryAssets} from './assets.mjs';
const hash=v=>createHash('sha256').update(typeof v==='string'||Buffer.isBuffer(v)?v:JSON.stringify(v)).digest('hex');
const text=(v,label)=>assert(typeof v==='string'&&v.trim(),`${label} required`);
const id=v=>{assert(/^[a-z][a-z0-9-]*$/.test(v),'Invalid ID');return v;};
const digestId=v=>{assert(/^[a-f0-9]{64}$/.test(v),'Invalid digest');return v;};
async function json(path){try{return JSON.parse(await readFile(path,'utf8'));}catch(e){if(e.code==='ENOENT')return null;throw e;}}
async function rows(path){try{return await Promise.all((await readdir(path)).filter(f=>f.endsWith('.json')).sort().map(f=>json(join(path,f))));}catch(e){if(e.code==='ENOENT')return [];throw e;}}
async function atomic(path,value){await mkdir(resolve(path,'..'),{recursive:true});const temp=path+'.'+randomUUID()+'.tmp';try{await writeFile(temp,typeof value==='string'?value:JSON.stringify(value,null,2)+'\n',{flag:'wx'});await rename(temp,path);}finally{await rm(temp,{force:true});}}
function humanInput(human){text(human?.by,'Actual human identity');text(human?.inputReference,'Actual human input reference');text(human?.note,'Human decision note');assert(/^\d{4}-\d{2}-\d{2}T.*(?:Z|[+-]\d{2}:\d{2})$/.test(human?.at??'')&&Number.isFinite(Date.parse(human.at)),'Human decision timestamp required');}
export function releaseReadiness(entry){
 const gaps=[];const rights=(value,label)=>{if(!value||typeof value!=='object'||!value.basis?.trim()||/unknown|pending|unverified/i.test(value.basis)||!value.source?.trim()||!value.attribution?.trim())gaps.push(`${label}: declared rights basis, source and attribution required`);};
 for(const path of entryAssets(entry)){const asset=entry.assets?.find(a=>a.path===path);rights(asset?.rights,path);}
 for(const [i,reuse] of (entry.dataReuse??[]).entries())rights(reuse.rights,`Reused dataset ${i+1}`);
 return gaps;
}
export function verifyWorkingRevision(entry,revision,{fragment='',assetDigests={}}={}){
 assert(revision&&entry.approval?.digest===revision.digest&&contentDigest(entry,{fragment,assetDigests})===revision.digest,`${entry.id}: working fragment, record or assets differ from approved revision`);
}
export function carryForward({entry,current=entry,fragment='',currentFragment=fragment,assetDigests={},evidence}){
 assert(evidence?.reference&&evidence?.authorizedBy&&Number.isFinite(Date.parse(evidence?.releasedAt)),'Verified baseline evidence required; migration cannot infer approval');
 assert(entry.approval?.by&&entry.approval?.at,'Original approval provenance required');
 const baseline=structuredClone(entry);baseline.publishedAt=evidence.releasedAt;const digest=contentDigest(baseline,{fragment,assetDigests});baseline.approval.digest=digest;
 const revision={id:entry.id,digest,entry:baseline,fragment,assetDigests,release:{at:evidence.releasedAt,authorizedBy:evidence.authorizedBy},provenance:evidence};
 let proposal=null;if(contentDigest(current,{fragment:currentFragment,assetDigests})!==digest){const proposed=structuredClone(current);proposed.status='review';delete proposed.approval;delete proposed.publishedAt;proposal={id:entry.id,entry:proposed,fragment:currentFragment,assetDigests,baselineDigest:digest,digest:contentDigest(proposed,{fragment:currentFragment,assetDigests}),state:'pending',origin:'Unmatched local changes retained during baseline migration'};}
 return {revision,proposal};
}
export async function loadReleaseState(directory=fileURLToPath(root)){
 const manifest=await json(join(directory,'content/releases/current.json'));assert(manifest,'Verified release manifest missing; production cannot use status-only selection');
 return {manifest,revisions:await rows(join(directory,'content/revisions/approved'))};
}
export function createReviewDesk({directory=fileURLToPath(root),clock=()=>new Date()}={}){
 const base=resolve(directory),content=join(base,'content'),approved=join(content,'revisions/approved'),proposals=join(content,'revisions/proposals'),decisions=join(content,'revisions/decisions');
 const entryPath=v=>join(content,'entries',id(v)+'.json');const packetPath=(v,d)=>join(proposals,id(v)+'-'+digestId(d)+'.json');
 const approvedPath=(v,d)=>join(approved,id(v)+'-'+digestId(d)+'.json');const decisionPath=(v,d)=>join(decisions,id(v)+'-'+digestId(d)+'.json');
 async function subject(entry,fragment){const assetDigests=Object.fromEntries(await Promise.all(entryAssets(entry).map(async path=>[path,hash(await readFile(join(base,'public',path)))])));if(entry.treatment.kind==='custom'&&fragment===undefined)fragment=await readFile(join(base,'src/exhibits',entry.treatment.template+'.html'),'utf8');return {fragment:fragment??'',assetDigests};}
 async function mutate(operation){await mkdir(content,{recursive:true});let lock;try{lock=await open(join(content,'.editorial.lock'),'wx');await lock.writeFile(JSON.stringify({pid:process.pid,at:clock().toISOString()}));}catch(e){if(e.code==='EEXIST')return {outcome:'conflict',reason:'Another editorial writer or interrupted lock is present.'};throw e;}try{return await operation();}catch(e){return {outcome:'failed',reason:e.message};}finally{await lock.close();await rm(join(content,'.editorial.lock'),{force:true});}}
 const api={
 async report(){const {manifest,revisions}=await loadReleaseState(base);const packets=await rows(proposals),recorded=await rows(decisions);const entries=await rows(join(content,'entries'));return {manifest,manifestDigest:hash(manifest),revisions,packets:packets.map(p=>{const baseline=revisions.find(r=>r.id===p.id&&r.digest===p.baselineDigest);const decision=recorded.find(d=>d.id===p.id&&d.digest===p.digest);let validation=[];try{validate({...p.entry,status:'review'});}catch(e){validation=[e.message];}return {...p,state:decision?.decision??p.state??'pending',decision,conflict:(entries.find(e=>e.id===p.id)?.approval?.digest??null)!==p.baselineDigest,readiness:[...validation,...releaseReadiness(p.entry)],changes:packetDiff(baseline,p)};}),unpacketized:entries.filter(e=>['draft','review'].includes(e.status)&&!packets.some(p=>p.id===e.id))};},
 propose({entry,fragment,baselineDigest=null}){return mutate(async()=>{validate(entry);assert(['draft','review'].includes(entry.status),'Proposals must be private drafts or review records');assert(!entry.approval&&!entry.release,'Proposal cannot carry approval or release');const current=await json(entryPath(entry.id));if((current?.approval?.digest??null)!==baselineDigest)return {outcome:'conflict',reason:'Approval baseline changed; reload and reconcile.'};const material=await subject(entry,fragment),digest=contentDigest(entry,material),path=packetPath(entry.id,digest);const existing=await json(path);if(existing)return {outcome:'unchanged',digest,packet:existing};const workload=await createDesk({directory:base,clock}).report();const replacesSlot=workload.queue.entries.some(row=>row.id===entry.id&&!row.digest);if(!replacesSlot&&workload.queue.count>=workload.queue.limit)return {outcome:'deferred',reason:'Unfinished review queue is full; finish or close an existing packet.'};const packet={id:entry.id,digest,baselineDigest,entry,...material,state:'pending',createdAt:clock().toISOString(),workingRecordHash:hash(current)};await atomic(path,packet);return {outcome:'created',digest,packet};});},
 decide(entryId,digest,decision,human){return mutate(async()=>{humanInput(human);assert(['keep','revise','reject'].includes(decision),'Decision must be keep, revise or reject');const packet=await json(packetPath(entryId,digest));assert(packet,'Unknown review packet');assert(contentDigest(packet.entry,packet)===digest,'Review packet changed after review');if(await json(decisionPath(entryId,digest)))return {outcome:'conflict',reason:'A human decision is already recorded; prepare a new revision.'};const current=await json(entryPath(entryId));if(packet.workingRecordHash&&hash(current)!==packet.workingRecordHash)return {outcome:'conflict',reason:'Working record changed after the packet was prepared; reconcile it.'};if((current?.approval?.digest??null)!==packet.baselineDigest)return {outcome:'conflict',reason:'Approval baseline changed; reconcile the proposal.'};
 if(decision==='keep'){
  validate({...packet.entry,status:'review'});assert(packet.entry.status==='review','Incomplete draft cannot be approved');const gaps=releaseReadiness(packet.entry);assert(!gaps.length,gaps.join('; '));const material=await subject(packet.entry,packet.fragment);assert(contentDigest(packet.entry,material)===digest,'Assets changed after review');
  const entry={...packet.entry,status:'published',publishedAt:human.at,approval:{by:human.by,at:human.at.slice(0,10),digest,inputReference:human.inputReference,note:human.note}};
  await atomic(approvedPath(entryId,digest),{id:entryId,digest,entry,...material});if(entry.treatment.kind==='custom')await atomic(join(base,'src/exhibits',entry.treatment.template+'.html'),material.fragment);await atomic(entryPath(entryId),entry);
 }else if(!packet.baselineDigest&&current&&['draft','review'].includes(current.status)){
  const material=await subject(current,packet.fragment);if(contentDigest(current,material)!==digest)return {outcome:'conflict',reason:'Draft changed since packet creation; preserve and reconcile.'};await atomic(entryPath(entryId),{...current,status:decision==='reject'?'retired':'draft'});
 }
 if(decision==='reject') {const path=join(content,'candidates',entryId+'.json'),candidate=await json(path);if(candidate){const next={...candidate,disposition:'rejected',dispositionReason:human.note,updatedAt:human.at};delete next.revision;await atomic(path,next);};}
 await atomic(decisionPath(entryId,digest),{id:entryId,digest,decision,human});return {outcome:'created',id:entryId,digest,decision};});},
 release({entries,withdrawals=[],expectedManifest,human}){return mutate(async()=>{humanInput(human);const state=await loadReleaseState(base);if(hash(state.manifest)!==expectedManifest)return {outcome:'conflict',reason:'Release manifest changed; review the new release baseline.'};const manifest={version:1,releasedAt:human.at,authorizedBy:human.by,inputReference:human.inputReference,note:human.note,entries,withdrawals};const selected=selectRelease([],{...state,manifest,now:clock()});for(const entry of selected.entries){assert(!releaseReadiness(entry).length,releaseReadiness(entry).join('; '));const revision=selected.revisions.get(entry.id),material=await subject(entry,revision.fragment);assert(contentDigest(entry,material)===revision.digest,'Released asset identity changed');}
 for(const revision of selected.revisions.values())await atomic(approvedPath(revision.id,revision.digest),{...revision,release:{at:human.at,authorizedBy:human.by,inputReference:human.inputReference}});await atomic(join(content,'releases/current.json'),manifest);return {outcome:'created',manifest};});}
 };return api;
}
export function packetDiff(baseline,proposal){const before=baseline?.entry?{...baseline.entry,share:shareCopy(baseline.entry)}:{};const after={...proposal.entry,share:shareCopy(proposal.entry)};const fields={claim:['title','question','answer','explanation','qualification','whyCare','guess','share'],data:['treatment','dataReuse'],sources:['evidence','assets']};return Object.fromEntries(Object.entries(fields).map(([group,keys])=>[group,[...keys.filter(key=>JSON.stringify(before[key])!==JSON.stringify(after[key])).map(key=>({field:key,before:before[key]??null,after:after[key]??null})),...(group==='claim'&&JSON.stringify(fragmentEditorialContent(baseline?.fragment))!==JSON.stringify(fragmentEditorialContent(proposal.fragment))?[{field:'custom fragment',before:fragmentEditorialContent(baseline?.fragment),after:fragmentEditorialContent(proposal.fragment)}]:[])]]));}
export function reviewIndex(report){return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="robots" content="noindex,nofollow"><title>Private editorial review</title><style>body{max-width:70rem;margin:3rem auto;padding:1rem;font:18px system-ui}pre{white-space:pre-wrap;overflow-wrap:anywhere}article{border-top:1px solid;padding:1rem 0}</style><h1>Private editorial review</h1><p>Local only. Approval and release are separate human decisions. <a href="/">Preview collection</a></p>${report.packets.filter(p=>!['reject','keep'].includes(p.state)).map(p=>`<article><h2>${esc(p.entry.title)}</h2><p>${esc(p.state)} · ${p.conflict?'Baseline conflict':'Baseline unchanged'}</p><p>Revision: ${esc(p.digest)}</p><p>Readiness: ${esc(p.readiness.join('; ')||'Structurally ready; factual and visual judgment still required')}</p>${p.entry.status==='review'?`<a href="/review/${esc(p.id)}/${esc(p.digest)}/">Preview exact revision</a>`:'<p>Complete this draft before preview.</p>'}<pre>${esc(JSON.stringify(p.changes,null,2))}</pre></article>`).join('')}${report.unpacketized.map(e=>`<article><h2>${esc(e.title)}</h2><p>${esc(e.status)} — prepare an exact revision packet before recording a decision.</p>${e.status==='review'?`<a href="/discoveries/${esc(e.id)}/">Preview discovery</a>`:''}</article>`).join('')}</html>`;}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)){
 const [command,...args]=process.argv.slice(2),desk=createReviewDesk();let result;
 if(command==='report')result=await desk.report();else if(command==='propose')result=await desk.propose(JSON.parse(await readFile(args[0],'utf8')));else if(command==='decide')result=await desk.decide(args[0],args[1],args[2],JSON.parse(await readFile(args[3],'utf8')));else if(command==='release')result=await desk.release(JSON.parse(await readFile(args[0],'utf8')));else throw new Error('Use report | propose PACKET.json | decide ID DIGEST keep|revise|reject HUMAN.json | release RELEASE.json');console.log(JSON.stringify(result,null,2));if(['failed','conflict'].includes(result.outcome))process.exitCode=1;
}
